//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class HospitalEntities : DbContext
{
    public HospitalEntities()
        : base("name=HospitalEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblAppointment> tblAppointments { get; set; }
    public virtual DbSet<tblDepartment> tblDepartments { get; set; }
    public virtual DbSet<tblDoctor> tblDoctors { get; set; }
    public virtual DbSet<tblEmail> tblEmails { get; set; }
    public virtual DbSet<tblHospital> tblHospitals { get; set; }
    public virtual DbSet<tblPatient> tblPatients { get; set; }
    public virtual DbSet<tblUser> tblUsers { get; set; }
}
