//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAppointment
{
    public int AppointmentID { get; set; }
    public string PatientUserName { get; set; }
    public string DoctorUserName { get; set; }
    public string AppointmentDate { get; set; }
    public string AppointmentTime { get; set; }
    public string Description { get; set; }
}

public partial class tblDepartment
{
    public int DepartmentID { get; set; }
    public Nullable<int> HospitalID { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Phone { get; set; }
}

public partial class tblDoctor
{
    public int DoctorID { get; set; }
    public Nullable<int> DepartmentID { get; set; }
    public string DoctorPhone { get; set; }
    public string DoctorEmail { get; set; }
    public string UserName { get; set; }
}

public partial class tblEmail
{
    public int EmailID { get; set; }
    public string UserNameTO { get; set; }
    public string UserNameFrom { get; set; }
    public string EmailText { get; set; }
}

public partial class tblHospital
{
    public int HospitalID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Contacts { get; set; }
}

public partial class tblPatient
{
    public int PatientID { get; set; }
    public int DoctorID { get; set; }
    public string Name { get; set; }
    public string UserEmail { get; set; }
    public string UserPhone { get; set; }
    public string UserName { get; set; }
}

public partial class tblUser
{
    public int UserID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string UserType { get; set; }
}
